### ISSUE TITLE
rm-seq test: get permission error when running bwa index

### ISSUE THREAD

**Issue by rguerillot** [rguerillot/RM-seq#5]
Running: bwa index /usr/local/lib/python3.5/dist-packages/RMseq/test_data/rpob.fna
[bwa_index] Pack FASTA... [bns_fasta2bntseq] fail to open file '/usr/local/lib/python3.5/dist-packages/RMseq/test_data/rpob.fna.pac' : Permission denied

**Comment by rguerillot** [comment]
Fixed

**Comment by jgroh** [comment]
I am getting the same error using bwa-0.7.15-r1140

`$ bwa index filename.fasta`
`[bwa_index] Pack FASTA... [bns_fasta2bntseq] fail to open file 'filename.fasta.pac' : Permission denied`

Is there a solution?

**Comment by rguerillot** [comment]
Hi, could you tell me what command you are using?

**Comment by jgroh** [comment]
bwa index <filename.fasta>

I resolved the issue: did not have write permission. Thanks
